title: Résumé
baseurl: "/resume/"
color: nord
exclude:
  - README.md
  - "README_zh-CN.md"
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - jekyll-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
  - Rakefile
  - vendor
  - port-hexo
